import Foundation
import PlayerCore

// MARK: - BundledSampleTrack
//
// F7 — the short, original sample track the app ships so a fresh install has
// something to press Play on (App Review 2.1(a): with no music files every
// control looked dead). The audio is `App/DwanimIt/Resources/dwanim it - Sample.m4a`,
// generated by `Tools/SampleTrack/make-sample-track.swift`; this is only the
// LOCATOR. Everything the session asks about the row — "is this queue URL the
// sample?", "what is its current URL for a persisted marker?", "should this launch
// seed it?" — is PlayerCore's `BundledTrack` / `FirstLaunchSampleSeeder`, pinned
// under `swift test`.
//
// The file's own stem, "dwanim it - Sample", is what the queue row shows, and the
// shared `Artist - Title` split renders it as artist "dwanim it", title "Sample" —
// the same pair the file's embedded tags carry.
//
// `locate` returns `nil` when the resource is missing from the bundle, and every
// caller degrades: no seeding, no Play Sample button, no crash.
enum BundledSampleTrack {

    /// The resource name (`Bundle.url(forResource:withExtension:)`), and what a
    /// persisted marker names.
    static let resourceName = "dwanim it - Sample"
    static let fileExtension = "m4a"

    /// Find the sample in `bundle` (the main bundle by default). `nil` when it
    /// does not ship.
    static func locate(in bundle: Bundle = .main) -> BundledTrack? {
        BundledTrack.locate(resourceName: resourceName, extension: fileExtension, in: bundle)
    }
}

// MARK: - SampleSeedStore
//
// The persisted "the sample has been seeded" flag behind `FirstLaunchSampleSeeder`.
// Set the first time the sample is placed in the queue; once set, the sample never
// reappears on its own (the empty state's Play Sample button re-adds it on
// demand). Lives in the same sandbox-container `UserDefaults` as the bookmarks.
final class SampleSeedStore: SampleSeedFlagStore {

    private static let defaultsKey = "app.dwanim.sampleSeeded.v1"
    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
    }

    var hasSeeded: Bool {
        get { defaults.bool(forKey: SampleSeedStore.defaultsKey) }
        set { defaults.set(newValue, forKey: SampleSeedStore.defaultsKey) }
    }
}
