import AVFoundation
import Foundation
import XCTest
import PlayerCore
@testable import PlaybackKit

// MARK: - BundledSampleTrackTests
//
// F7 — the COMMITTED sample track the app bundles (`App/DwanimIt/Resources/
// dwanim it - Sample.m4a`, generated by `Tools/SampleTrack/make-sample-track.swift`).
// It is the first thing a new user (or App Reviewer) presses Play on, so this
// pins the artefact itself, not the script: the format the README promises, the
// size budget, the embedded title/artist, and — the load-bearing part — that the
// REAL `AVAudioEnginePlayer` plays it: the render clock advances (muted through
// `SilentRealPlayback`, like every other real-playback test here).
//
// The file is reached relative to this source file, so the test reads the very
// bytes that will ship rather than a copy.
@MainActor
final class BundledSampleTrackTests: XCTestCase {

    /// `SkinKit/Tests/PlaybackKitTests/<this file>` → repo root → the resource.
    private static let sampleURL: URL = {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // PlaybackKitTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // SkinKit
            .deletingLastPathComponent() // repo root
            .appendingPathComponent("App/DwanimIt/Resources/dwanim it - Sample.m4a")
    }()

    func testTheSampleIsCommittedAtThePathTheAppBundles() {
        XCTAssertTrue(FileManager.default.fileExists(atPath: Self.sampleURL.path),
                      "missing: \(Self.sampleURL.path) — run Tools/SampleTrack/make-sample-track.swift")
    }

    func testTheSampleIsAShortStereo44kAACWithinTheSizeBudget() throws {
        let file = try AVAudioFile(forReading: Self.sampleURL)
        let format = file.processingFormat
        XCTAssertEqual(format.sampleRate, 44_100)
        XCTAssertEqual(format.channelCount, 2)
        let seconds = Double(file.length) / format.sampleRate
        XCTAssertEqual(seconds, 20, accuracy: 1.0, "about twenty seconds")

        let bytes = try XCTUnwrap(
            FileManager.default.attributesOfItem(atPath: Self.sampleURL.path)[.size] as? Int
        )
        XCTAssertLessThanOrEqual(bytes, 400_000, "≲ 400 KB")
        XCTAssertGreaterThan(bytes, 100_000, "and not suspiciously tiny (silence encodes to almost nothing)")

        // The container/codec the README names: MPEG-4 audio holding AAC.
        let asset = AVURLAsset(url: Self.sampleURL)
        let tracks = try awaitValue { try await asset.loadTracks(withMediaType: .audio) }
        let track = try XCTUnwrap(tracks.first)
        let descriptions = try awaitValue { try await track.load(.formatDescriptions) }
        let formatID = descriptions.first.map { CMFormatDescriptionGetMediaSubType($0) }
        XCTAssertEqual(formatID, kAudioFormatMPEG4AAC, "AAC inside .m4a")
    }

    func testTheSampleCarriesTitleAndArtistTags() throws {
        let asset = AVURLAsset(url: Self.sampleURL)
        let metadata = try awaitValue { try await asset.load(.commonMetadata) }
        func value(_ key: AVMetadataKey) throws -> String? {
            let items = AVMetadataItem.metadataItems(from: metadata, withKey: key, keySpace: .common)
            guard let item = items.first else { return nil }
            return try awaitValue { try await item.load(.stringValue) }
        }
        XCTAssertEqual(try value(.commonKeyTitle), "Sample")
        XCTAssertEqual(try value(.commonKeyArtist), "dwanim it")
    }

    func testTheSampleIsMusicNotATestTone() throws {
        // A test tone is one frequency for its whole length; a piece changes. Read
        // the decoded PCM and check that the loudest 0.5 s windows do not all share
        // one dominant period — cheap, and enough to catch "we shipped a sine".
        let file = try AVAudioFile(forReading: Self.sampleURL)
        let frames = AVAudioFrameCount(file.length)
        let buffer = try XCTUnwrap(AVAudioPCMBuffer(pcmFormat: file.processingFormat, frameCapacity: frames))
        try file.read(into: buffer)
        let samples = try XCTUnwrap(buffer.floatChannelData?[0])
        let n = Int(buffer.frameLength)
        XCTAssertGreaterThan(n, 0)

        // RMS: audible, not clipping.
        var sum: Float = 0
        for i in 0..<n { sum += samples[i] * samples[i] }
        let rms = (sum / Float(n)).squareRoot()
        XCTAssertGreaterThan(rms, 0.03, "audible")
        XCTAssertLessThan(rms, 0.5, "not a wall of sound")

        // Dominant period (zero-crossing rate) per 0.5 s window, over the body.
        let window = Int(file.processingFormat.sampleRate / 2)
        var rates: [Int] = []
        var start = window
        while start + window < n - window {
            var crossings = 0
            for i in (start + 1)..<(start + window) where (samples[i - 1] < 0) != (samples[i] < 0) {
                crossings += 1
            }
            rates.append(crossings)
            start += window
        }
        let distinct = Set(rates.map { $0 / 20 }) // bucket to ignore jitter
        XCTAssertGreaterThanOrEqual(distinct.count, 3,
                                    "the spectrum moves over time (zero-crossing rates \(rates))")
    }

    /// The load-bearing assertion: the real engine plays it and the clock moves.
    func testTheRealPlayerPlaysTheSampleAndTheClockAdvances() throws {
        try XCTSkipUnless(
            AudioOutputDeviceProbe.hasOutputDevice(),
            "no audio output route on this machine — real playback cannot be observed"
        )
        let player = SilentRealPlayback.makePlayer()
        let core = PlayerCore(engine: player)
        core.load([Track(url: Self.sampleURL, title: "dwanim it - Sample")])

        core.play()
        XCTAssertTrue(core.isPlaying, "the sample loads and starts")
        XCTAssertEqual(player.sampleRateHz, 44_100)
        XCTAssertEqual(player.channelCount, 2)
        XCTAssertEqual(player.duration, 20, accuracy: 1.0)

        let deadline = Date(timeIntervalSinceNow: 2)
        while player.currentTime < 0.4, Date() < deadline {
            RunLoop.main.run(until: Date(timeIntervalSinceNow: 0.05))
        }
        XCTAssertGreaterThanOrEqual(player.currentTime, 0.4,
                                    "the render clock advances — audio is really being rendered")
        core.pause()
    }

    // MARK: - Async helper

    /// Run an async AVFoundation load to completion from a synchronous test.
    private func awaitValue<T: Sendable>(_ body: @escaping @Sendable () async throws -> T) throws -> T {
        let box = ResultBox<T>()
        let done = DispatchSemaphore(value: 0)
        Task.detached {
            do { box.set(.success(try await body())) } catch { box.set(.failure(error)) }
            done.signal()
        }
        done.wait()
        return try XCTUnwrap(box.get()).get()
    }
}

private final class ResultBox<T: Sendable>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Result<T, Error>?
    func set(_ v: Result<T, Error>) { lock.lock(); value = v; lock.unlock() }
    func get() -> Result<T, Error>? { lock.lock(); defer { lock.unlock() }; return value }
}
